<?php
/** @package Sisstc::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ClienteMap.php");

/**
 * ClienteDAO provides object-oriented access to the tbcliente table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sisstc::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ClienteDAO extends Phreezable
{
	/** @var int */
	public $Cpf;

	/** @var string */
	public $Nome;

	/** @var string */
	public $Email;

	/** @var date */
	public $Datadenascimento;

	/** @var string */
	public $Cep;

	/** @var string */
	public $Logradouro;

	/** @var string */
	public $Numero;

	/** @var string */
	public $Cidade;

	/** @var string */
	public $Bairro;

	/** @var string */
	public $Estado;

	/** @var string */
	public $Telefone;


	/**
	 * Returns a dataset of Tbcompra objects with matching Cpfcliente
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetCpfclienteTbcompras($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "tbcompra_ibfk_1", $criteria);
	}

	/**
	 * Returns a dataset of Tbpagamento objects with matching Cpfcliente
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetCpfclienteTbpagamentos($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "tbpagamento_ibfk_1", $criteria);
	}


}
?>