<?php
/** @package Sisstc::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ProdutoMap.php");

/**
 * ProdutoDAO provides object-oriented access to the tbproduto table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sisstc::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ProdutoDAO extends Phreezable
{
	/** @var int */
	public $Idproduto;

	/** @var string */
	public $Codigodebarras;

	/** @var string */
	public $Nome;

	/** @var float */
	public $Preco;

	/** @var float */
	public $Custo;

	/** @var int */
	public $Quantidade;

	/** @var string */
	public $Unidade;


	/**
	 * Returns a dataset of Tbprodutosparacompra objects with matching Idproduto
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdprodutoTbprodutosparacompras($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "tbprodutosparacompra_ibfk_1", $criteria);
	}


}
?>